branches:
  only:
    - master
    - development
    - OS-X-build
os:
  - osx
language: java
script: "mvn -f ./com.codeaffine.xiliary.releng/pom.xml clean verify"
before_script:
  - chmod a+x prepare.sh
  - source ./prepare.sh
after_success: 
  - chmod a+x deploy.sh
  - ./deploy.sh
